### ISSUE TITLE
Can I use Unite db v9 with an older version of Qiime2?

### ISSUE THREAD

**Issue by tarunaaggarwal** [colinbrislawn/unite-train#4]
Hi @colinbrislawn - thank you for building classifiers for the newest version of the Unite db (v9). I was wondering if these classifiers are compatible with `qiime2-2021.8`? I'd like to update my fungal taxonomy for the rep seqs that were generated using `qiime2-2021.8`. Please advice. 

Thank you,
Taruna

**Comment by colinbrislawn** [comment]
You could always take a rep set sequence file made with an older version of Qiime2 and classify it with a newer version of Qiime2. What needs to match is the sci-kit bio versions used to train the classifier and then classify the sequence. (The origin of the seqs does not matter technically.)

Newer versions of Qiime2 include performance improvements and new features, so it may be worth updating to the newest version.

**Comment by colinbrislawn** [comment]
I'm going to close for now. Feel free to reopen if you want to continue the discussion!
