### ISSUE TITLE
97% Identity UNITE Classifier 

### ISSUE THREAD

**Issue by seqing-answers** [colinbrislawn/unite-train#8]
Just posting this as requested -- 

97% UNITE eukaryote classifier would be fantastic, whenever you find the time! 

I'm sure others would also love the Fungi UNITE classifiers as well in 97% identity. 

Thanks so much again!

**Comment by colinbrislawn** [comment]
Sure thing!

97% classifiers have been added here:
https://github.com/colinbrislawn/unite-train/releases/tag/v10.0-v04.04.2024-qiime2-2024.2 

The last one is still building, but the first three are here now. Once all these are done I'll close this issue.

Let me know if these work for you!
